---
abstract: 'Perl extension for http://www.reddit.com'
author:
  - 'three18ti <three18ti@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Reddit
requires:
  Data::Dumper: 0
  HTTP::Cookies: 0
  JSON: 0
  LWP::UserAgent: 0
  Moose: 0
  common::sense: 0
  perl: 5.010001
version: 0.001
