--- #YAML:1.0
name:               Reddit
version:            0.11
abstract:           Perl extension for http://www.reddit.com
author:
    - jon <jon@>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    common::sense:   0
    Data::Dumper:    0
    HTTP::Cookies:   0
    JSON:            0
    LWP::Simple:     0
    LWP::UserAgent:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
